workflows:
  ios_unsigned:
    name: ProFile IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate project
        script: |
          xcodegen generate

      - name: Build
        script: |
          xcodebuild \
          -project ProFileApp.xcodeproj \
          -scheme ProFileApp \
          -sdk iphoneos \
          -archivePath build/app.xcarchive \
          CODE_SIGNING_ALLOWED=NO \
          archive

      - name: Create IPA
        script: |
          mkdir Payload
          cp -R build/app.xcarchive/Products/Applications/*.app Payload/
          zip -r ProFile_unsigned.ipa Payload

    artifacts:
      - ProFile_unsigned.ipa
