workflows:
  ios_unsigned:
    name: ProFile IPA
    max_build_duration: 60
    instance_type: mac_mini_m2

    scripts:
      - name: Install XcodeGen
        script: |
          brew update
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate

      - name: List projects (debug)
        script: |
          ls
          ls *.xcodeproj

      - name: Build archive
        script: |
          set -e

          xcodebuild \
            -project ProFileApp.xcodeproj \
            -scheme ProFileApp \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/ProFile.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -R build/ProFile.xcarchive/Products/Applications/*.app Payload/
          zip -r ProFile_unsigned.ipa Payload

    artifacts:
      - ProFile_unsigned.ipa
