name: ProFileApp

targets:
  ProFileApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - ios_src
    resources:
      - web
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.profile.app
        INFOPLIST_FILE: ios_src/Info.plist
