name: WebPanelApp
options:
  bundleIdPrefix: com.betao

targets:
  WebPanelApp:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: ios_src
    resources:
      - path: web
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.betao.webpanelapp
        INFOPLIST_FILE: ios_src/Info.plist
